# Generated by Django 2.0 on 2018-04-28 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100)),
                ('method', models.IntegerField(choices=[(1, 'POST'), (2, 'GET')])),
                ('data_type', models.IntegerField(choices=[(1, 'JSON'), (2, 'FORM'), (3, 'XML')])),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_sign', models.IntegerField(blank=True, choices=[(1, 'SIGN'), (2, 'NOT SIGN')], null=True)),
                ('developer', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('access_id', models.CharField(max_length=50)),
                ('access_key', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Environment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('assertion', models.TextField()),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Api')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'PASS'), (2, 'FAIL'), (3, 'SKIP'), (4, 'ERROR')])),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Api')),
            ],
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='TestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('case_num', models.IntegerField(null=True)),
                ('pass_num', models.IntegerField(null=True)),
                ('fail_num', models.IntegerField(null=True)),
                ('error_num', models.IntegerField(null=True)),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestPlan')),
            ],
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestReport'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestPlan'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TestPlan'),
        ),
        migrations.AddField(
            model_name='step',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestCase'),
        ),
        migrations.AddField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
    ]
