# Generated by Django 2.0 on 2018-05-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180507_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': '接口管理', 'verbose_name_plural': '接口管理'},
        ),
        migrations.AlterModelOptions(
            name='environment',
            options={'verbose_name': '环境设置', 'verbose_name_plural': '环境设置'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterModelOptions(
            name='projectenv',
            options={'verbose_name': '项目设置', 'verbose_name_plural': '项目设置'},
        ),
        migrations.AlterModelOptions(
            name='sign',
            options={'verbose_name': '签名设置', 'verbose_name_plural': '签名设置'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': '步骤管理', 'verbose_name_plural': '步骤管理'},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '用例管理', 'verbose_name_plural': '用例管理'},
        ),
        migrations.AlterModelOptions(
            name='testcaseresult',
            options={'verbose_name': '用例结果', 'verbose_name_plural': '用例结果'},
        ),
        migrations.AlterModelOptions(
            name='testplan',
            options={'verbose_name': '测试计划', 'verbose_name_plural': '测试计划'},
        ),
        migrations.AlterModelOptions(
            name='testreport',
            options={'verbose_name': '测试报告', 'verbose_name_plural': '测试报告'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='description',
        ),
        migrations.AddField(
            model_name='projectenv',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Sign', verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='sign',
            name='描述',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='data_type',
            field=models.IntegerField(choices=[(1, 'JSON'), (2, 'FORM')], verbose_name='数据类型'),
        ),
        migrations.AlterField(
            model_name='api',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='api',
            name='method',
            field=models.IntegerField(choices=[(1, 'POST'), (2, 'GET')], verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='api',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='api',
            name='request_body',
            field=models.TextField(blank=True, null=True, verbose_name='请求数据'),
        ),
        migrations.AlterField(
            model_name='api',
            name='response_body',
            field=models.TextField(blank=True, null=True, verbose_name='响应数据'),
        ),
        migrations.AlterField(
            model_name='api',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Url地址'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开发负责人'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='access_id',
            field=models.CharField(max_length=50, verbose_name='AccessID'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='access_key',
            field=models.CharField(max_length=50, verbose_name='AccessKey'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Environment', verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectenv',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Url地址'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='step',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Api', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='step',
            name='assertion',
            field=models.TextField(verbose_name='断言'),
        ),
        migrations.AlterField(
            model_name='step',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestCase', verbose_name='用例'),
        ),
        migrations.AlterField(
            model_name='step',
            name='data',
            field=models.TextField(verbose_name='数据'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Api', verbose_name='接口'),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestReport', verbose_name='测试报告'),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='status',
            field=models.IntegerField(choices=[(1, 'PASS'), (2, 'FAIL'), (3, 'SKIP'), (4, 'ERROR')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestPlan', verbose_name='测试计划'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Environment', verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='case_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='用例数量'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='error_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='出错数量'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='fail_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='失败数量'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='testreport',
            name='pass_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='通过数量'),
        ),
    ]
