# Generated by Django 2.0 on 2018-05-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180507_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
        migrations.AddField(
            model_name='step',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
    ]
