# Generated by Django 2.0 on 2018-05-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180509_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TestPlan'),
        ),
    ]
