# Generated by Django 2.0 on 2018-05-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180510_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testreport',
            name='name',
        ),
        migrations.AlterField(
            model_name='step',
            name='sn',
            field=models.IntegerField(blank=True, null=True, verbose_name='序号'),
        ),
    ]
