# Generated by Django 2.0 on 2018-05-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180511_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='接口名称')),
                ('api_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='接口Url')),
                ('api_headers', models.CharField(blank=True, max_length=100, null=True, verbose_name='请求头')),
                ('api_data', models.CharField(blank=True, max_length=100, null=True, verbose_name='请求数据')),
                ('api_response', models.CharField(blank=True, max_length=100, null=True, verbose_name='响应内容')),
                ('status', models.CharField(blank=True, max_length=10, null=True, verbose_name='状态')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Step', verbose_name='步骤')),
            ],
            options={
                'verbose_name': '步骤结果',
                'verbose_name_plural': '步骤结果',
            },
        ),
        migrations.RemoveField(
            model_name='testcaseresult',
            name='api',
        ),
        migrations.RemoveField(
            model_name='testcaseresult',
            name='test_plan',
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Api', verbose_name='测试用例'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='test_case_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TestCaseResult', verbose_name='测试用例结果'),
        ),
    ]
